version: '3'

services:
  springboot-hjj:
    build: .
    container_name: springboot-hjj
    ports:
      - "8082:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
