version: '3'
services:
  tomcat-hjj:
    build: .
    container_name: tomcat-hjj
    ports:
      - "8081:8080"
    restart: always
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    networks:
      - tomcat-network

networks:
  tomcat-network:
    driver: bridge
      
