version: '3'
services:
  nginx-hjj:
    build: .
    container_name: nginx-hjj
    ports:
      - "80:80" 
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge